---
title: "GOVT670 Project Plan"
author: "Yuka Chen and Concillia Mpofu"
date: "`r Sys.Date()`"
output: html_document
bibliography: References-YukaC-ConcilliaM.bib
link-citations: true
nocite: '@*'
---

# Short Summary of Project Plan
We are planning to combine multiple dataset to see if there are any factor causes the car crash in the DC areas. We will include, road condition, traffic lights, speed camera, income, etc in to our data set.

# 1. Datasets

- https://opendata.dc.gov/datasets/DCGIS::street-lights/about 
- https://opendata.dc.gov/datasets/DCGIS::crash-details-table/explore
- https://opendata.dc.gov/datasets/DCGIS::crashes-in-dc/explore?location=38.893706 
- https://opendata.dc.gov/datasets/acs-economic-characteristics-dc-ward/explore?location=38.940965 
- https://opendata.dc.gov/datasets/DCGIS::wards-from-2022/explore?location=38.893755 
- https://opendata.dc.gov/datasets/economic-acs-characteristics-2011-to-2015/explore

# 2. Points From Meeting with Professor

- Particular cars
- Zip code level -80 level for income
- Censes block level - 400 level for income
- Infrustracure data, plan structures
- Plan road closure - what road is close or going to close. Doc dc transportation
- Traffic violation - tickets, flags whether is the police or automated intervention (camera)
- RA funded through de doc - she can find info or data for us - LAB
- MAR Geocoder - jut for DC - provide different type of the location - it will tell you the location info you need - its an software

# References


<div id="refs"></div>