---
title: "data_cleaning"
author: "Yuka Chen"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup-chunk, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      cache = TRUE)
```
# loading packages 
```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(tidyverse)
library(ISLR)
library(tidymodels)
library(DAAG)
library(party)
library(rpart)
library(rpart.plot)
library(mlbench)
library(caret)
library(pROC)
library(tree)
library(broom)
library(kableExtra)
library(MASS)
library(arm)
library(leaps)
library(ggthemr)
```

# Load data from Github - saved from OpenDataDC
```{r include=FALSE}
########### set up path for dataset ########
urlRemote  <- "https://media.githubusercontent.com/media/"
pathGithub <- "yjchen9596/data/main/GOVT670/" 

##https://github.com/yjchen9596/data/tree/main/GOVT670 ## path to where I store the data
########## laoding data ###################
economic_dc_ward <- 
  paste0(urlRemote,
         pathGithub, 
         "ACS_Economic_Characteristics_DC_Ward.csv") |> 
  read_csv()


car_crash <- paste0(urlRemote,
                    pathGithub,
                    "Crashes_in_DC.csv") |> read_csv()
car_crash_details <-  paste0(urlRemote, 
                             pathGithub, 
                             "Crash_Details_Table.csv") |> read_csv()
pavement_making <- paste0(urlRemote,
                          pathGithub,
                          "Pavement_Marking.csv") |>  read_csv()
street_lights <- paste0(urlRemote,
                        pathGithub,
                        "Street_Lights.csv") |> read_csv()
traffic_camera <- paste0(urlRemote,
                         pathGithub,
                         "Traffic_Camera.csv") |> read_csv()
traffic_monitor_location <- paste0(urlRemote,
                                   pathGithub,
                                   "Traffic_Monitoring_Stations.csv") |> read_csv()
traffic_signal_cabinet <- paste0(urlRemote,
                                 pathGithub,
                                 "Traffic_Signal_Cabinets.csv") |> read_csv()
```

#StreetLights with Cases
```{r}

library(janitor)
street.lights <- street_lights %>%
  tabyl(WARD) |> 
  mutate(WARD = recode(WARD, 
                       "1" = "Ward 1",
                       "2" = "Ward 2",
                       "3" = "Ward 3",
                       "4" = "Ward 4",
                       "5" = "Ward 5",
                       "6" = "Ward 6",
                       "7" = "Ward 7",
                       "8" = "Ward 8")) |> 
    mutate(WARD = ifelse(is.na(WARD), "Unknown",WARD)) |> 
  mutate(WARD = as.character(WARD),
         WARD = if_else(WARD %in% c("Null", "UNKNOWN"), "Unknown", WARD)) |> 
  filter(WARD != "Unknown")


traffic.cases <- cases.after2010 %>%
  filter(time_period == "Night"|time_period =="Evening") |> 
      mutate(WARD = if_else(WARD %in% c("Null", "UNKNOWN"), "Unknown", WARD)) |> 
  tabyl(WARD) |> 
  filter(WARD != "Unknown")

# street.lights %>%
#              mutate(WARD = paste("Ward", WARD))

street.lights |> 
  left_join(traffic.cases, by = "WARD") |> 
  rename(s.lights = n.x, 
         s.lights.pct = percent.x,
         s.lights.valid.pct = valid_percent,
         actd.cases =  n.y,
         actd.cases.pct = percent.y) -> lights.accident.df

write_rds(lights.accident.df, file = "lights.accident.rds")
```


## Plot StreetLights with Cases
```{r}
library(gridExtra)

cases.after2010<- read_rds("cases.after2010.rds")

cases.after2010 |> 
  mutate(PERSONTYPE = recode(PERSONTYPE, 
                       "0" = "Unknown", 
                     "Occupant o" = "Unknown", 
                     "Other" = "Unknown", 
                     "Unknown" = "Unknown",
                     "Electric M" = "ElectricalCar"),
                     WARD = as.character(WARD),
                     PERSONTYPE = as.character(PERSONTYPE)) |> 
  mutate(FATAL = ifelse(FATAL == "Y", 1, 0)) |> 
    filter(AGE >= 16 & AGE < 90) |> 
  mutate(WARD = if_else(WARD %in% c("Null", "UNKNOWN"), "Unknown", WARD),
         FATAL = if_else(FATAL == 1, 0, 1),
         SPEEDING_INVOLVED = if_else(SPEEDING_INVOLVED == 1, 0, 1)) |> 
        filter(PERSONTYPE !=  "Unknown" &  PERSONTYPE !=  "Witness" & PERSONTYPE !=  "Reporting") |> 
  dplyr::select(FATAL, everything()) |> 
  rename_all(toupper)  |> 
  filter(WARD != "Unknown") -> cases.after20102
```

```{r}
p1 <- cases.after20102 |> 
  ggplot(aes(x = WARD, color = WARD))+
  geom_bar(fill = "white")+
  labs(y = "Numbers of Accidents",
       x = "",
       title = "Distribution of Cases")+
   scale_y_discrete(position = "right")+
  coord_flip() + 
  theme(legend.position="none")+
  theme(plot.title = element_text(hjust = 0.5))

p2 <- street_lights |>
   mutate(WARD = recode(WARD, 
                       "1" = "Ward 1",
                       "2" = "Ward 2",
                       "3" = "Ward 3",
                       "4" = "Ward 4",
                       "5" = "Ward 5",
                       "6" = "Ward 6",
                       "7" = "Ward 7",
                       "8" = "Ward 8")) |> 
    mutate(WARD = ifelse(is.na(WARD), "Unknown",WARD)) |> 
  mutate(WARD = as.character(WARD),
         WARD = if_else(WARD %in% c("Null", "UNKNOWN"), "Unknown", WARD)) |> 
  filter(WARD != "Unknown") |> 
  drop_na(WARD) |> 
  ggplot(aes(x = WARD, color = WARD))+
  geom_bar(fill = "white")+
  labs(y = "Numbers of Street Lights",
       x= "")+
  scale_y_discrete(position = "right")+
  coord_flip() + 
  theme(legend.position="none")
  
ggthemr("fresh")
grid.arrange(p1, p2, nrow=2)
```


### combine data
```{r}

library(lubridate)
car_crash |> 
  left_join(car_crash_details, by = c("CRIMEID", "CCN")) -> a1
# map_df(a1, ~sum(is.na(.)))

a1 |> 
   dplyr::select(-c("LOCATIONERROR", "LASTUPDATEDATE","MPDLATITUDE","MPDLONGITUDE","STREETSEGID", "TODATE","EVENTID","MAR_ADDRESS", "ROADWAYSEGID", "MPDGEOX","MPDGEOY")) -> a2
# 
# map_df(a2, ~sum(is.na(.)))
a2 |> 
  drop_na() |> 
  mutate(FROMDATE =  as_datetime(FROMDATE),
         date = as_date(FROMDATE),
         time =  hour(FROMDATE),
         month = month(FROMDATE),
         year = year(FROMDATE))-> no_na_all_car_crashes_data

no_na_all_car_crashes_data |> 
  mutate(time_period = case_when(
    time > 6 & time < 12 ~ "Morning",
    time >= 12 & time < 17 ~ "Afternoon",
    time >= 17 & time < 21 ~ "Evening",
    time >=21 | time <= 6 ~ "Night")) -> no_na_all_car_crashes_data
  
## save data
# write_csv(no_na_all_car_crashes_data, file = "no_na_all_car_crashes_data.csv")
no_na_all_car_crashes_data |> 
   dplyr::filter(MAJORINJURY == "Y") -> major_injured_cases
```

# Plot


## time period
```{r}
ggthemr("fresh")

no_na_all_car_crashes_data |> 
  ggplot(mapping = aes(x = time_period, fill = time_period))+
  geom_bar()+
  labs(y = "Case Numbers", x = "Time Period",
       title = "Car Crashes by Time Period",
       legend = "Time Period"
)+
  theme_light()+
  theme(plot.title = element_text(hjust = 0.5))
```

## months cases
```{r}
car_crashes_data_summary <- no_na_all_car_crashes_data |> 
 mutate(monthly_cases = floor_date(date, unit = "month")) %>%            
  count(monthly_cases) %>%           # group data by week and count rows per group (creates column 'n')
  tidyr::complete(                  # ensure all weeks are present, even those with no cases reported
    monthly_cases = seq.Date(          # re-define the "weekly_cases" column as a complete sequence,
      from = min(monthly_cases),       # from the minimum date
      to = max(monthly_cases),         # to the maxiumum date
      by = "month"),                   # by weeks
    fill = list(n = 0))             # fill-in NAs in the n counts column with 0

```

```{r } 
overall.plot<- ggplot(car_crashes_data_summary, aes(x = monthly_cases, y = n))+
  geom_point()+
  geom_smooth()+
  labs(title = "Car Crashes Cases by Months \nfrom 1990 to 2021",
       y = "Numbers of Cases",
       x = "Months")+
  theme_light()+
  theme(plot.title = element_text(hjust = 0.5))

before2000 <- car_crashes_data_summary |> 
  filter(n > 0 & monthly_cases < "2000-01-01") ## the first record is in 1900

before2000.plot <- ggplot(before2000, aes(x = monthly_cases, y = n))+
  geom_point()+
  geom_smooth()+
    labs(title = "Car Crashes Cases by Months \nbefore 2000",
       y = "Numbers of Cases",
        x = "Months")+
  theme(plot.title = element_text(hjust = 0.5))

between2000n2010 <- car_crashes_data_summary |> 
  filter(n > 0 & monthly_cases > "2000-01-01" & monthly_cases < "2010-01-01") ## the first record is in 1900

between2000n2010.plot <- ggplot(between2000n2010, aes(x = monthly_cases, y = n))+
  geom_point()+
  geom_smooth()+
  labs(title = "Car Crashes Cases by Months \nbetween 2000 to 2010",
       y = "Numbers of Cases",
        x = "Months")+
  theme(plot.title = element_text(hjust = 0.5))

after2010 <- car_crashes_data_summary |> 
  filter(n > 0 & monthly_cases > "2010-01-01") ## the first record is in 1900

after2010.plot <- ggplot(after2010, aes(x = monthly_cases, y = n))+
  geom_point()+
  geom_smooth()+
    labs(title = "Car Crashes Cases by Months \nafter 2010",
       y = "Numbers of Cases",
        x = "Months")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
ggthemr("fresh")
grid.arrange(overall.plot, before2000.plot, between2000n2010.plot, after2010.plot, nrow = 2, ncol = 2)

```


```{r}

no_na_all_car_crashes_data |> 
   dplyr::filter(year > 2010) -> cases.after2010

#write_csv(cases.after2010, file = "cases.after2010.csv")
#write_rds(cases.after2010, file = "cases.after2010.rds", compress = "gz")
```



```{r}
colnames(no_na_all_car_crashes_data)
```


```{r}
df_analysis<- no_na_all_car_crashes_data %>%
dplyr::select(-c(PERSONID,MAR_ID, NEARESTINTSTREETNAME, NEARESTINTROUTEID, YCOORD, XCOORD, LONGITUDE,LATITUDE, ADDRESS, FROMDATE, REPORTDATE, X, Y, CCN,  MEASURE,OFFSET,VEHICLEID, date, time, year, CRIMEID, ROUTEID, INTAPPROACHDIRECTION, INVEHICLETYPE, LICENSEPLATESTATE  ))
```

```{r}
df_analysis |> 
  group_by(PERSONTYPE) |> 
  summarise(n=n()) |> 
  knitr::kable()
```

